import React,{useState,useEffect}from"react";
import{useNavigate,useParams}from"react-router-dom";
import{doc,getDoc,collection,getDocs,query,where}from"firebase/firestore";
import{db}from"../firebase/config";
import{exportarPDFCurso}from"../utils/helpers";
import Dashboard from"../components/Dashboard";
import TomarAsistencia from"../components/TomarAsistencia";
import Temario from"../components/Temario";
import Agenda from"../components/Agenda";
export default function Curso(){const{id}=useParams();const navigate=useNavigate();const[curso,setCurso]=useState(null);const[registros,setRegistros]=useState({});const[tab,setTab]=useState("dashboard");const[tomarAsistencia,setTomarAsistencia]=useState(false);useEffect(()=>{cargarCurso();},[id]);async function cargarCurso(){const snap=await getDoc(doc(db,"cursos",id));if(snap.exists())setCurso({id:snap.id,...snap.data()});const q=query(collection(db,"registros"),where("cursoId","==",id));const rSnap=await getDocs(q);const regs={};rSnap.docs.forEach(d=>{regs[d.data().fecha]={id:d.id,...d.data()};});setRegistros(regs);}if(!curso)return React.createElement("div",{style:{padding:"2rem",textAlign:"center",color:"#888"}},"Cargando...");if(tomarAsistencia)return React.createElement(TomarAsistencia,{curso,registros,onGuardar:()=>{setTomarAsistencia(false);cargarCurso();},onVolver:()=>setTomarAsistencia(false)});return React.createElement("div",{style:{minHeight:"100vh",background:"#f8f8f6",padding:"1rem"}},React.createElement("div",{style:{maxWidth:720,margin:"0 auto"}},React.createElement("div",{style:{display:"flex",alignItems:"center",gap:12,marginBottom:4}},React.createElement("button",{style:{background:"none",border:"none",fontSize:22,cursor:"pointer",color:"#888",padding:0},onClick:()=>navigate(-1)},"←"),React.createElement("h2",{style:{flex:1,fontSize:20,fontWeight:600,color:"#1a1a1a"}},curso.nombre),React.createElement("button",{style:{background:"#378ADD",color:"white",border:"none",borderRadius:8,padding:"8px 14px",fontSize:13,fontWeight:600,cursor:"pointer"},onClick:()=>setTomarAsistencia(true)},"Tomar asistencia")),React.createElement("div",{style:{display:"flex",borderBottom:"1px solid #eee",marginBottom:"1.25rem"}},["dashboard","temario","agenda"].map(t=>React.createElement("button",{key:t,style:{padding:"8px 20px",fontSize:14,cursor:"pointer",border:"none",background:"none",color:tab===t?"#378ADD":"#999",borderBottom:tab===t?"2px solid #378ADD":"2px solid transparent",marginBottom:-1,fontFamily:"inherit",fontWeight:tab===t?600:400,textTransform:"capitalize"},onClick:()=>setTab(t)},t))),tab==="dashboard"&&React.createElement(Dashboard,{curso,registros}),tab==="temario"&&React.createElement(Temario,{curso,registros,onActualizar:cargarCurso}),tab==="agenda"&&React.createElement(Agenda,{cursoId:id})));}
